### PR TITLE
Translator switch

### PR DESCRIPTION
**Pull request by victoragcosta**
Refatoradas Linhas e instruções para que sejam classes com métodos nos lugares mais corretos
Usada herança de instrução para não criar o enorme switch feio e ilegível
Mudados deques de Line e Instruction para Line* e Instruction* (funcionam melhor)
resolvidos conflitos de passagem de dados que geravam dois ponteiros apontando para o mesmo objeto (culpa da mudança para ponteiros)
Resolvidos vazamentos de memória por conta da refatoração (valgrind approved)
Só falta desativar textos de debug.
EDIT: desativei os debug, mas descobri que vaza memória quando traduz algo com erros...

### CODE REVIEW

**Comment by victoragcosta** [comment]
Coloquei o trabalho no moodle já como failsafe

**Comment by AndreLaranjeira** [comment]
I'm taking a look at the file changes before testing anything in the code. The code seems very well built in general. I do, however, have some concerns:

* Shouldn't your assembly functions "burn" the parameters in the stack since your translation just pops eax?

* The EscreverString function assumes that all chars are saved in 1 byte when they are actually saved in 4 bytes and doesn't look for a '\n' char as a possible end of string.

* I don't understand why the MULT translation creates a pushf instruction and then right after creates a popf instruction. Maybe it should have created the pushf before the mult instruction?

* Shouldn't the JZ instruction also have a CMP instruction preceding it (just to be safe)?

* The INPUT translation should push the address where the int will be saved before calling the assembly function. And then it should not move the result to eax.

I'll pull the branch, run some aditional tests and, _if I have time_ see what I can do about some of these concerns.

**Comment by AndreLaranjeira** [comment]
I pulled the branch. The program compiles, but the 'make test' option fails... I'll see if I can push a commit with at least some fixes until noon.

**Review by AndreLaranjeira — CHANGES_REQUESTED** [review]
Some changes are still needed before we can merge this branch into master.

**Comment by AndreLaranjeira** [comment]
Wait, the makefile works. There was just a file missing.

**Comment by victoragcosta** [comment]
Maybe I forgot to burn the parameters
I'll review the EscreverString, but I'll not stop at \n, maybe \0. This is assembly, we let the programmer take care of all the stuff.
The pushf and popf was so I could get the flags and read the overflow flag... Is there a jump if overflow?
the JZ is taking the flags generated with the test (test generates flag zero if there's no OF on). 
I'll refactor the Input function

**Comment by AndreLaranjeira** [comment]
Very good changes. I still think that the error logging for strings bigger than 100 is kind of a workaround, but everything else seems perfect!

**Review by AndreLaranjeira — APPROVED** [review]

**Pull request merged**
